### PR TITLE
openFrameworks examples

### PR DESCRIPTION
**Pull request by orgicus**
added openFrameworks ports of the existing Processing examples

### CODE REVIEW

**Comment by cvalenzuela** [comment]
This is awesome!! thanks, @orgicus! 🔥 

Just to maintain consistency across all examples, can you add a license to all the files?

**Comment by orgicus** [comment]
@cvalenzuela Just to make sure I understand: I should add this header to `main.cpp` and `ofApp.cpp` within the the two projects:

```c++
// Copyright (C) 2018 Cristobal Valenzuela
//
// This file is part of RunwayML.
//
// RunwayML is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// RunwayML is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with RunwayML.  If not, see <http://www.gnu.org/licenses/>.
//
// ===========================================================================

// RUNWAY
// www.runwayml.com

```

(which is already in ofApp.h) right ?
(or should I copy LICENSE into the openpose and im2txt folders ?)

Thank you :)

**Comment by cvalenzuela** [comment]
yes! just add that part to the examples!
No need to add the LICENSE file

**Comment by orgicus** [comment]
@cvalenzuela done :)

**Comment by cvalenzuela** [comment]
looks great! I'm going to go on and merge this before actually trying it, just in case more people want to contribute similar examples. I'm not very familiar with OF so I hope I won't take too much time to try it!

thanks @orgicus!

**Pull request merged**
